server:
  port: 8091
spring:
  profiles:
    #开发环境
    active: dev
  freemarker:
    template-loader-path:  classpath:/templates/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
    suffix: .ftl
management:
  health:
    mail:
      enabled: false
  server:
    port: 54001