server:
  port: 8093
spring:
  profiles:
    #开发环境
    active: dev
    #测试环境
    #    active: test
    #生产环境
  #    active: prod
  freemarker:
    template-loader-path:  classpath:/templates/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
    suffix: .ftl
